# a = 5 / 0

# try:
#     a = 5/0
# except:
#     print("an error happened")



# try:
#     a = 5/0
# except Exception as e:
#     print(e)



# try:
#     a = 5/1
#     b = a + "10"
# except ZeroDivisionError as e:
#     print(e)
# except TypeError as e:
#     print(e)


# try:
#     a = 5/1
#     b = a + 4
# except ZeroDivisionError as e:
#     print(e)
# except TypeError as e:
#     print(e)
# else:
#     print("Fine")
# finally:
#     print("cleaning up...")